---
abstract: 'Captures emails sent via Email::Send for testing, with Tie::DataDumper'
author:
  - 'Nobuo Danjou <nobuo.danjou@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec::Functions: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Send-Test-DataDumper
no_index:
  directory:
    - inc
    - t
requires:
  Email::Send: 0
  Email::Simple: 0
  Filter::Util::Call: 0
  Tie::DataDumper: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
